# Generated by Django 5.2.6 on 2025-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_companies_handbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company_slug',
            field=models.SlugField(blank=True, max_length=155, null=True),
        ),
    ]
