# Generated by Django 5.2.6 on 2025-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_slugify_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
