# Generated by Django 5.2.6 on 2025-10-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_adding_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company_slug',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=155, unique=True)),
                ('company_slug', models.SlugField(blank=True, max_length=155, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='companies.company'),
        ),
    ]
