# Generated by Django 5.2.6 on 2025-09-04 19:23

import django.db.models.deletion
import handbook_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=155, unique=True)),
                ('pdf_file', models.FileField(upload_to='handbook_files/', validators=[handbook_app.validators.validate_file_extension])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
