# Generated by Django 5.2.6 on 2025-09-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook_app', '0001_companies_handbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook', to='handbook_app.handbook')),
            ],
        ),
    ]
