# Generated by Django 5.2.6 on 2025-09-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook_app', '0002_faq_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='handbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='handbook_app.handbook'),
        ),
    ]
