# Generated by Django 5.2.6 on 2025-10-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_owner_user'),
        ('handbook_app', '0003_changed_related_name_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbooks', to='companies.company'),
        ),
    ]
